config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searches#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
     resource :favorites, only: [:create, :destroy]#上のdoと一緒にいいねで追加
     resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update,:create]do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end#フォロアーフォロー追加

  resources :chats, only: [:show, :create] #DM

 get "home/about"=>"homes#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image#追加
  belongs_to :user
  
  has_many :view_counts, dependent: :destroy #閲覧カウント

  has_many :book_comments,dependent: :destroy#コメント
  has_many :favorites, dependent: :destroy#いいね追加

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)#いいね追加
    favorites.where(user_id: user.id).exists?
  end


  def self.search(search, word)
    if search == "forward_match"
                  @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
                  @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
                  @book = Book.where("#{word}")
    elsif search == "partial_match"
                  @book = Book.where("title LIKE?","%#{word}%")
    else
                 @book = Book.all
    end
   end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/chat.rb
class Chat < ApplicationRecord
  
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  
  
end

app/models/searche.rb
class Searche < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :view_counts, dependent: :destroy #閲覧カウント

  has_many :user_rooms #DMここから
  has_many :chats
  has_many :rooms, through: :user_rooms　#ここまで　   

  has_many :books, dependent: :destroy#追加
  #belongs_to :books
  has_many :book_comments,dependent: :destroy#コメント
  has_many :favorites, dependent: :destroy#いいねで追加

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使用
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image


  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }#追加



  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.search(search,word)
    if search == "forward_match"
                 @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
                 @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
                 @user = User.where("#{word}")
    elsif search == "partial_match"
                 @user = User.where("name LIKE?","%#{word}%")
    else
                 @user = User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  
  belongs_to :user
  belongs_to :room
  
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  
belongs_to :user
belongs_to :book
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :is_matching_login_user,only:[:edit, :update]

  def show
    @book = Book.find(params[:id])
    @user=@book.user
    @books = Book.new#投稿フォームで追加
    @book_comment=BookComment.new

 #閲覧カウントここから
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.view_counts.create(book_id: @book.id)
    end #ここまで
  end

  def index
    @books = Book.includes(:favorites).sort {|a,b| b.favorites.size <=> a.favorites.size}
    @book=Book.new
    @user=current_user


  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
       @user=current_user
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

# ここからアクセス制限
  def is_matching_login_user
    @book=Book.find(params[:id])
    if @book.user!=current_user
    redirect_to books_path
    end
  end
  # ここまで追加

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :reject_non_related, only: [:show]
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.changes
    @chat = Chat.new(room_id: @room.id)
  end
  def create
    @chat = current_user.chats.new(chat_params)
    render :validater unless @chat.save
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

  def reject_non_related
    user = User.find(params[:id])
    unless current_user.following?(user) && user.following?(current_user)
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  

  def show
    @book= Book.new#他人の詳細、投稿フォーム
    @user = User.find(params[:id])
    @books = @user.books
    @users = User.all
  end

  def index
    @users = User.all
    @book = Book.new
  end


  def edit
    @user = User.find(params[:id])#追加
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>

    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>

          <% end %>
        </td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.body %></td>

<!--いいね-->
　    <td id="favorite_buttons_<%= book.id %>">
　　　<%= render "favorites/favorite", book: book %>
      </td>


<!--コメント-->
     <td>
       <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
     </td>

   <!--閲覧カウント-->
     <td class="view-count">閲覧数: <%= book.view_counts.count %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>


  <% if @book.errors.any? %>
 <h3> <%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book,url: book_path(@book), method: :patch  do |f| %>


  		<%= render 'form', book: @book %>

<% end %>

  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>

  <% if @book.errors.any? %>
 <h3> <%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>




  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
      
      
      
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>

  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @books %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>

            <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>

<!--いいね追加-->
      <td id="favorite_buttons_<%= @book.id %>">
　　　<%= render "favorites/favorite", book: @book %>
      </td>

      <!--閲覧カウント-->
     <td class="view-count">閲覧数: <%= @book.view_counts.count %></td>

<!--ここまで-->


        </tr>
      </table>

      <!--コメント-->
      <!--コメント一覧部分-->

     <div id="comment_form">
     <%= render 'book_comments/post_comments', book: @book %>
     </div>

     <div class="new-comment">
       <%= render 'book_comments/form',book: @book, book_comment: @book_comment %>
      </div>

    </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: right;'><%= @chat.message %></p>");
$('input[type=text]').val("")

app/views/chats/show.html.erb
<h1 id="room" data-room="<%= @room.id %>" data-user="<%= current_user.id %>">
<%= @user.name %> さんとのチャット</h1>

<div class="message" style="width: 400px;">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>

<div class="errors">
  <%= render "layouts/errors", obj: @chat %>
</div>

<%= form_with model: @chat, data: {remote: true} do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
<% end %>

app/views/chats/validater.js.erb
$('.errors').html("<%= j(render 'layouts/errors', obj: @chat) %>");

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= render 'relationships/follobutton', user: user %></td>
        <td><%= link_to 'Show', user %></td>


      </tr>
    <% end %>



  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>

  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>

	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to "#{user.followings.count}", user_followings_path(user.id) %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to "#{user.followers.count}",  user_followers_path(user.id) %></th>
  </tr>
</table>

 <div class='row'>
   <%= render 'relationships/follobutton', user: user %>

   <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
   <% end %>
 </div>



<div class='row'>
  <% if user == current_user %>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

<h2>User info</h2>
<%= render 'info', user: current_user %>

<h2 class="mt-3">New book</h2>
<%= render 'books/form', book: @book %>

 </div>

<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<%= render 'index',users: @users %>

  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>